# Generated by Django 3.0.8 on 2020-07-05 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='cabin',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='embarked',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='fare',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='parch',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='passenger_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unknown')], default='U', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='sibsp',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='survived',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='ticket',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='ticket_class',
            field=models.IntegerField(null=True),
        ),
    ]
